### ISSUE TITLE
Documentation link results in 404

### ISSUE THREAD

**Issue by Guriido** [Raschka-research-group/coral-pytorch#8]
The link to the documentation in the README seems dead: http://rasbt.github.io/coral_pytorch
Is the documentation available somewhere else?

Regards,

**Comment by rasbt** [comment]
Ah, sorry, I recently moved the project from my personal to my research group GitHub account. I forgot to update the links in certain places. The correct link is https://Raschka-research-group.github.io/coral_pytorch
